"use strict";
var actions = {
  LATEST_RETRIEVED : "LATEST_RETRIEVED",
  POPULAR_RETRIEVED : "POPULAR_RETRIEVED",
  SEARCH_RETRIEVED : "SEARCH_RETRIEVED",
  DETAILS_RETRIEVED : "DETAILS_RETRIEVED",
  ERROR : "MANGA_ERROR"
};
export default actions;
