"use strict";
var actions = {
  LATEST_RETRIEVED : "LATEST_RETRIEVED",
  POPULAR_RETRIEVED : "POPULAR_RETRIEVED",
  SEARCH_RETRIEVED : "SEARCH_RETRIEVED",
  ERROR : "ERROR"
};
export default actions;
